---

- hosts: all
  become: true
  tasks:
  - debug: msg="Installing bluemix client utils"

  - name: "Install jq"
    package:
      name: jq
      update_cache: yes

  - name: Get latest bx cli url
    shell: curl -s https://clis.ng.bluemix.net/all_versions  | jq --raw-output '.[0].binaries["linux64"].url'
    register: bx_url
    args:
      warn: false

  - name: Get blumix cli tarball
    get_url:
      url: "{{ bx_url.stdout }}"
      dest: /root/
      mode: 0755
    register: bx_tarball

  - name: untar bx cli tarball
    unarchive:
      src: "{{ bx_tarball.dest }}"
      dest: /root/
      remote_src: yes

  - name: install bluemix cli using provided script
    command: /root/Bluemix_CLI/install_bluemix_cli

  - name: configure bx cli to not send usage information
    command: /usr/local/bin/bluemix config --usage-stats-collect false

  - name: install bluemix plugins
    command: /usr/local/bin/bluemix plugin install "{{ item }}" -r Bluemix
    with_items:
      - auto-scaling
      - container-service
      - container-registry
      - cloud-functions
